--- 
title: "Forestry Management Geodatabase Technical Manual"
author: "US Army Corps of Engineers"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: 
  This technical manual was created to document the development of the Forestry
  Management Database. 
biblio-style: apalike
csl: chicago-fullnote-bibliography.csl
editor_options: 
  markdown: 
    wrap: 72
---
```{r library, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
```
--- 
```{r import, include=FALSE}
QA_Tools_df <- read.csv("data/QA_Tools.csv")
```


```{r table_functions, include=FALSE}
params_table <- function(QA_Tools_df, tool, caption) {
  param_names <- c("Parameter", "Description","Type", "Required")
  tool_dd <- filter(QA_Tools_df, tool == !!tool) %>%
             select(parameter:required)
  kable(tool_dd, col.names = param_names,
        caption = caption)

}
```


# Overview {-}

This technical manual documents the methods used to develop the FMG-toolbox. 
